[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.0"

[[bin]]
name = "day1_1"
path = "src/day1_1.rs"

[[bin]]
name = "day1_2"
path = "src/day1_2.rs"
